import { useState, useEffect } from 'react';
import { supabase } from '../../config/SupabaseClient'; 
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // Updated import syntax for modern bundlers
import './staffreport.css';

export default function StaffReports({ tickets = [] }) {
  const [userName, setUserName] = useState('');
  
  // States for Date Selection
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  
  // States for Document View
  const [isReportGenerated, setIsReportGenerated] = useState(false);
  const [filteredTickets, setFilteredTickets] = useState([]);
  const [summaryData, setSummaryData] = useState([]);

  useEffect(() => {
    const fetchUser = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        setUserName(user.user_metadata?.full_name || user.email.split('@')[0]);
      }
    };
    fetchUser();
  }, []);

  const handleGenerateReport = (e) => {
    e.preventDefault();
    if (!startDate || !endDate) return;

    const start = new Date(startDate);
    const end = new Date(endDate);
    
    // Set end date to the end of the selected day to ensure inclusive filtering
    end.setHours(23, 59, 59, 999);

    // 1. Filter tickets based on date range
    const matchingTickets = tickets.filter(ticket => {
      const ticketDate = new Date(ticket.created_at);
      return ticketDate >= start && ticketDate <= end;
    });

    // 2. Generate Summary Data (Group by Category, Count, Sort Descending)
    const summaryCounts = matchingTickets.reduce((acc, ticket) => {
      const cat = ticket.category || 'Uncategorized';
      acc[cat] = (acc[cat] || 0) + 1;
      return acc;
    }, {});

    const sortedSummary = Object.entries(summaryCounts)
      .map(([category, count]) => ({ category, count }))
      .sort((a, b) => b.count - a.count);

    setFilteredTickets(matchingTickets);
    setSummaryData(sortedSummary);
    setIsReportGenerated(true);
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      
      // --- PDF Header ---
      doc.setFillColor(6, 71, 50); // Brand Green
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text("Tatua Sasa", 14, 22);
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Issue Resolution & Analytics Report", 14, 32);
      
      // --- Dates & Meta ---
      doc.setTextColor(51, 51, 51);
      doc.setFontSize(10);
      doc.text(`Generated By: ${userName}`, 14, 50);
      doc.text(`Reporting Period: ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`, 14, 56);
      doc.text(`Total Issues Logged: ${filteredTickets.length}`, 14, 62);

      let finalY = 75;

      if (filteredTickets.length > 0) {
        // --- SUMMARY TABLE ---
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(6, 71, 50);
        doc.text("Issue Summary (Highest to Lowest)", 14, finalY);
        
        const summaryColumns = ["Issue Category", "Total Occurrences"];
        const summaryRows = summaryData.map(item => [
          item.category.replace('_', ' ').toUpperCase(),
          item.count
        ]);

        // Use the imported autoTable function directly
        autoTable(doc, {
          startY: finalY + 5,
          head: [summaryColumns],
          body: summaryRows,
          headStyles: { fillColor: [248, 250, 252], textColor: [51, 65, 85] },
          theme: 'grid',
          styles: { font: 'helvetica', fontSize: 10, cellPadding: 6 },
        });

        finalY = doc.lastAutoTable.finalY + 20;

        // --- DETAILED LOG TABLE ---
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(6, 71, 50);
        doc.text("Detailed Issue Log", 14, finalY);

        const logColumns = ["Date Raised", "Category", "Subject/Title"];
        const logRows = filteredTickets.map(ticket => [
          new Date(ticket.created_at).toLocaleDateString(),
          (ticket.category || 'N/A').replace('_', ' '),
          ticket.title || ticket.subject || 'Untitled Issue'
        ]);

        autoTable(doc, {
          startY: finalY + 5,
          head: [logColumns],
          body: logRows,
          headStyles: { fillColor: [6, 71, 50], textColor: [255, 255, 255] },
          alternateRowStyles: { fillColor: [244, 247, 246] },
          styles: { font: 'helvetica', fontSize: 9, cellPadding: 5 },
        });
      } else {
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text("No issues were raised during this specific time period.", 14, finalY);
      }

      // Triggers native browser download
      doc.save(`Tatua_Sasa_Report_${startDate}_to_${endDate}.pdf`);
      
    } catch (error) {
      console.error("PDF Generation Error: ", error);
      alert("Failed to generate the PDF. Please check the console for details.");
    }
  };

  return (
    <div className="reports-container">
      {!isReportGenerated ? (
        /* --- SELECTION SCREEN --- */
        <div className="report-selection-screen">
          <h2>
            Welcome {userName ? userName.split(' ')[0] : 'User'},<br/>
            for what duration would you like to generate a report for?
          </h2>
          
          <form className="date-form" onSubmit={handleGenerateReport}>
            <div className="date-inputs">
              <div className="date-group">
                <label htmlFor="startDate">Start Date</label>
                <input 
                  type="date" 
                  id="startDate" 
                  value={startDate} 
                  onChange={(e) => setStartDate(e.target.value)} 
                  required 
                />
              </div>
              <div className="date-group">
                <label htmlFor="endDate">End Date</label>
                <input 
                  type="date" 
                  id="endDate" 
                  value={endDate} 
                  onChange={(e) => setEndDate(e.target.value)} 
                  required 
                />
              </div>
            </div>
            
            <button type="submit" className="primary-btn" style={{ marginTop: '10px' }}>
              Generate Report
            </button>
          </form>
        </div>
      ) : (
        /* --- DOCUMENT VIEW SCREEN --- */
        <div className="document-view-container">
          
          <div className="document-header-actions">
            <button className="back-btn-report" onClick={() => setIsReportGenerated(false)}>
              &larr; Back to Date Selection
            </button>
          </div>

          <div className="report-document">
            {/* Document Navbar */}
            <div className="doc-navbar">
              <h1>Tatua Sasa</h1>
              <div className="doc-dates">
                Report Period: {new Date(startDate).toLocaleDateString()} &mdash; {new Date(endDate).toLocaleDateString()}
              </div>
            </div>

            {filteredTickets.length === 0 ? (
              <p style={{ textAlign: 'center', color: '#64748b', marginTop: '50px' }}>
                No issues were recorded during this time period.
              </p>
            ) : (
              <>
                {/* 1. Raw Data Table */}
                <h3 className="doc-section-title">Detailed Issue Log</h3>
                <table className="doc-table">
                  <thead>
                    <tr>
                      <th>Date Raised</th>
                      <th>Category</th>
                      <th>Subject</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredTickets.map(ticket => (
                      <tr key={ticket.id}>
                        <td>{new Date(ticket.created_at).toLocaleDateString()}</td>
                        <td style={{ textTransform: 'capitalize' }}>{(ticket.category || '').replace('_', ' ')}</td>
                        <td>{ticket.title || ticket.subject}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>

                {/* 2. Summary Table */}
                <h3 className="doc-section-title" style={{ marginTop: '40px' }}>Issue Summary Overview</h3>
                <table className="doc-table" style={{ maxWidth: '400px' }}>
                  <thead>
                    <tr>
                      <th>Issue Type</th>
                      <th>Total Occurrences</th>
                    </tr>
                  </thead>
                  <tbody>
                    {summaryData.map((item, idx) => (
                      <tr key={idx}>
                        <td style={{ textTransform: 'capitalize' }}>{item.category.replace('_', ' ')}</td>
                        <td><strong>{item.count}</strong></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}
          </div>

          <button className="download-pdf-btn" onClick={handleDownloadPDF}>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
              <polyline points="7 10 12 15 17 10"></polyline>
              <line x1="12" y1="15" x2="12" y2="3"></line>
            </svg>
            Download PDF Report
          </button>

        </div>
      )}
    </div>
  );
}